export const RESUME_DATA = {
  personal: {
    name: 'Sandesh Kumar',
    title: 'Pirate Developer | AI/ML Engineer',
    email: 'sandeshkr07@gmail.com',
    phone: '+91-9682962562',
    location: 'Bhubaneswar, India',
    github: 'https://github.com/Sandeshkumar0/Sandesh_portfolio',
    linkedin: 'https://linkedin.com/in/sandesh-kumar',
  },
  education: {
    school: 'Kalinga Institute of Industrial Technology (KIIT)',
    degree: 'B.Tech in Computer Science',
    cgpa: 8.96,
    period: 'Aug 2023 - Jul 2027',
  },
  skills: {
    languages: ['Python', 'Java', 'JavaScript', 'C++', 'SQL'],
    backend: ['Django', 'Node.js', 'Express.js', 'MongoDB', 'Redis', 'Nginx'],
    frontend: ['React.js', 'Tailwind CSS', 'REST APIs', 'JWT'],
    ml: ['TensorFlow', 'OpenCV', 'CNN', 'Face Tracking'],
    cloud: ['AWS', 'Render', 'Google Colab'],
  },
  experience: [
    {
      company: 'Emesys Consultancy',
      position: 'Full Stack Developer Intern',
      period: 'Feb 2026 - Apr 2026',
      description: 'Built Smart Health System with pharmacy mapping and digital prescription ecosystem.',
      tech: ['React.js', 'Node.js', 'Express.js', 'MongoDB'],
    },
    {
      company: 'Tata Steel',
      position: 'AI/ML Developer Intern',
      period: 'May 2025 - Jul 2025',
      description: 'Developed CNN-based facial expression detection with 89% accuracy.',
      tech: ['TensorFlow', 'OpenCV', 'Python'],
    },
  ],
  projects: [
    {
      id: 1,
      name: 'abacus',
      tagline: 'Interactive Calculation Tool',
      description: 'A clean web-based abacus project focused on simple interaction and visual clarity.',
      tech: ['HTML', 'CSS', 'JavaScript'],
      date: '2026',
      link: 'https://github.com/Sandeshkumar0/abacus',
      dangerLevel: 5,
    },
    {
      id: 2,
      name: 'aerodrive_rental',
      tagline: 'Full-Stack Car Rental Platform',
      description: 'A rental platform for browsing cars, handling bookings, and managing user journeys.',
      tech: ['JavaScript', 'Node.js', 'Auth', 'Booking'],
      date: '2026',
      link: 'https://github.com/Sandeshkumar0/aerodrive_rental',
      dangerLevel: 4,
    },
    {
      id: 3,
      name: 'FAR-AWAY',
      tagline: 'Travel Packing List App',
      description: 'A lightweight trip-planning app for tracking items before a journey begins.',
      tech: ['React', 'JavaScript', 'State'],
      date: '2026',
      link: 'https://github.com/Sandeshkumar0/FAR-AWAY',
      dangerLevel: 4,
    },
    {
      id: 4,
      name: 'eUdyaan-Backend',
      tagline: 'Backend for eUdyaan Platform',
      description: 'Backend services for the eUdyaan platform, supporting data, APIs, and product logic.',
      tech: ['Backend', 'APIs', 'Database'],
      date: '2026',
      link: 'https://github.com/Sandeshkumar0/eUdyaan-Backend',
      dangerLevel: 3,
    },
  ],
};
